# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhtAutoMarkir
                                 A QGIS plugin
 Automatis membuat panjang markir dengan menggunakan poligon evapot (PHT)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-22
        copyright            : (C) 2026 by Allasca Dev
        email                : y.allasca@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PhtAutoMarkir class from file PhtAutoMarkir.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pht_auto_markir import PhtAutoMarkir
    return PhtAutoMarkir(iface)
