# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhtAutoMarkirDialog
                                 A QGIS plugin
 Automatis membuat panjang markir dengan menggunakan poligon evapot (PHT)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Allasca Dev
        email                : y.allasca@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import csv
from qgis.utils import iface

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "pht_auto_markir_dialog_base.ui")
)


class PhtAutoMarkirDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(PhtAutoMarkirDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushButton.clicked.connect(self.proses)

    def proses(self):
        self.progressBar.reset()

        petak = self.textEdit_3.toPlainText()
        anak_petak = self.textEdit_4.toPlainText()
        nama_file = self.textEdit_5.toPlainText()
        kelas_hutan = self.textEdit_6.toPlainText()
        rph = self.textEdit_7.toPlainText()
        bkph = self.textEdit_8.toPlainText()
        bh = self.textEdit_9.toPlainText()

        # petak = "PETAK"
        # anak_petak = "ANAKPETAK"
        # nama_file = "TESMANTUP"
        # kelas_hutan = "KELASHUTAN"

        print(f" {petak}, {anak_petak}, {nama_file}")
        output_file = os.path.join(f"D:\\", f"{nama_file}.csv")

        data = [["Petak", "Anak petak", "Kelas hutan", "Jarak", "RPH", "BKPH", "BH"]]
        layer = iface.activeLayer()
        raw_features = layer.getFeatures()

        features = list(raw_features)
        jumlah = len(features)

        print(jumlah)
        for i in range(jumlah):
            geom1 = features[i].geometry()
            for j in range(i + 1, jumlah):
                geom2 = features[j].geometry()
                if geom1.intersects(geom2):
                    percent = i / float(jumlah) * 100
                    self.progressBar.setValue(int(percent))
                    if features[i][petak] != features[j][petak]:
                        continue
                    p = features[i][petak]
                    ap1 = features[i][anak_petak].replace(p, "")
                    ap2 = features[j][anak_petak].replace(p, "")
                    kh1 = features[i][kelas_hutan]
                    kh2 = features[j][kelas_hutan]
                    krph = features[i][rph]
                    kbkph = features[i][bkph]
                    kbh = features[i][bh]
                    intersection_geom = geom1.intersection(geom2)
                    m = intersection_geom.length()
                    print(f" | {p} | {ap1}/{ap2} | {kh1}/{kh2} | {int(m)}")
                    data.append(
                        [p, f"{ap1}/{ap2}", f"{kh1}/{kh2}", int(m), krph, kbkph, kbh]
                    )

        with open(output_file, mode="w", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerows(data)
        self.progressBar.setValue(100)
